FROM ubuntu:14.04
MAINTAINER Pronto Tools

RUN apt-get update --fix-missing

RUN apt-get install -y \
  build-essential \
  libpq-dev \
  python2.7 \
  python2.7-dev \
  python-pip \
  postgresql-client \ 
  postgresql-contrib \
  postgresql-9.3

RUN pip install \
  Django==1.9.7 \ 
  psycopg2==2.6.1 \
  uWSGI==2.0.13.1
